### ISSUE TITLE
Problems with response::json()

### ISSUE THREAD

**Issue by schnti** [jenstornell/kirby-html-minifier#15]
Plugin not working with JSON Responses.

```
kirby()->routes(array(
	array(
		'pattern' => 'info.json',
		'action' => function () {

                        [...]

			return response::json(['settings' => 'TEST']);

		}
	)
));
```

Returns `<{"settings":"TEST"}` with an `<` at the beginning.

Adding `json` to the blacklist is working.

```
private function isBlacklisted($format, $blacklist = ['js', 'css', 'json'])
	{
		return in_array($format, $blacklist);
	}
```

This is not working:
`c::set('plugin.html.minifier.blacklist', ['info.json']);`

**Comment by jenstornell** [comment]
I close this as I added another issue of tests for different filetypes. It will not be solved before Kirby 3.
