### ISSUE TITLE
whitespace after opening element

### ISSUE THREAD

**Issue by stereonom** [jenstornell/kirby-html-minifier#19]
In your `tiny-html-minifier.php` file:
```
    // Compact content
    function compact($content, $name, $element) {
        if($this->skip != 0) {
            $name = $this->skipName;
        } else {
            $content = preg_replace('/\s+/', ' ', $content);
        }
```

Why do you `preg_replace` with a space?
I get `<div class="foo"> </div>` with that space but I want `<div class="foo"> </div>` to make something in css like `.foo:empty { display: none; }`.

**Comment by stereonom** [comment]
Oh, I get it…Now i don't have any spaces anywhere.

But it would still be nice to get opening and closing tags without a space.

**Comment by jenstornell** [comment]
Maybe it helps if you update with the latest version of `tiny-html-minifier.php`?

- https://github.com/jenstornell/tiny-html-minifier/blob/master/tiny-html-minifier.php
- https://github.com/jenstornell/tiny-html-minifier/pull/19

**Comment by stereonom** [comment]
Thanks!.

With the option `collapse_whitespace => true` it's working as expected. Thanks!
