### ISSUE TITLE
Maybe close plugin

### ISSUE THREAD

**Issue by jenstornell** [jenstornell/kirby-html-minifier#4]
If all the issues are fixed with KirbyCompress I think it solves the same thing a bit better.

https://github.com/iksi/KirbyCompress

**Comment by janstieler** [comment]
Hi,
https://github.com/eXpl0it3r/kirby-krb
makes the job also good but also with CSS and JS.

Cheers

**Comment by jenstornell** [comment]
@janstieler Thanks! I have changed my mind. Instead of closing this plugin I have now updated it and replaced the old minify engine to a new one.
